# Generated by Django 5.1.3 on 2024-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_servicorealizado_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'saida')], max_length=7)),
                ('data', models.DateTimeField()),
                ('metodoPagamento', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicosRealizados', models.ManyToManyField(blank=True, to='api.servicorealizado')),
            ],
        ),
    ]
