# Generated by Django 5.1.3 on 2024-11-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicorealizado',
            name='data',
        ),
    ]
