# Generated by Django 5.1.3 on 2024-11-17 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_servicorealizado_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
